### PR TITLE
TelegramTarget - Added Layout support for BaseUrl + BotToken + ChatId

### PR DESCRIPTION
**Pull request by snakefoot**
Now `BaseUrl` + `BotToken` + `ChatId` can be rendered using NLog Layout-logic, so one can get values from appsetting.json or app.config

### CODE REVIEW

**Review by sopheakmorm — APPROVED** [review]

**Comment by snakefoot** [comment]
@Sopheakmorm Thank you for accepting the PullRequest. Any chance for making a new release:

`dotnet pack -c Release`

**Comment by snakefoot** [comment]
@Sopheakmorm Polite poke to have new build published to [nuget](https://www.nuget.org/packages/NLog.Telegram.Format/).

**Comment by snakefoot** [comment]
@sopheakmorm Another polite poke for updated nuget-package [NLog.Telegram.Format](https://www.nuget.org/packages/NLog.Telegram.Format/)

**Comment by snakefoot** [comment]
@sopheakmorm Any chance to get new nuget-package published  [NLog.Telegram.Format](https://www.nuget.org/packages/NLog.Telegram.Format/) ?

**Pull request merged**
