### PR TITLE
Added support for NetStandard2.0

### PR DESCRIPTION
**Pull request by snakefoot**

### CODE REVIEW

**Comment by sopheakmorm** [comment]
We already have: https://github.com/Sopheakmorm/NLog.Telegram.Format.Core

**Comment by snakefoot** [comment]
This merges them into one, that is easier to maintain.

**Comment by snakefoot** [comment]
And also updates to the new csproj format that are cleaner, and makes it easy to perform dotnet pack to create nuget package

**Comment by sopheakmorm** [comment]
Okay deal

**Comment by snakefoot** [comment]
Thank you for the merge. Have created PR #2 with better NLog Layout-support.

**Pull request merged**
